server:
  port: 8080

spring:
  datasource:
    # ?????????????SSMS?????????????????? master ??
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;DatabaseName=master
    username: sa
    password: wjy050623
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# MyBatis ?? (???????????)
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # ????? user_name ???? Java ? userName
